Color bug causing shell to wrap before it should

diff --git a/parts/4_prompt b/parts/4_prompt
--- a/parts/4_prompt
+++ b/parts/4_prompt
@@ -38,49 +38,49 @@ function int_ninjab_help_4_prompt() {
 cat <<EOF
    Current Format: [(SYSTEM TYPE)] USER@HOST [dynamic section] { CURRENT DIRECTORY }$"
    SYSTEM TYPE: (Will only be visible if sysinfo is defined.
-     $(set_color red)Red$(set_color)          == Critical system
-     $(set_color yellow)Yellow$(set_color)       == Production system
-     $(set_color green)Green$(set_color)        == Test system
+     \[$(set_color red)\]Red\[$(set_color)\]          == Critical system
+     \[$(set_color yellow)\]Yellow\[$(set_color)\]       == Production system
+     \[$(set_color green)\]Green\[$(set_color)\]        == Test system
    USER:      (also sets the base color for the prompt)
-     $(set_color red)Red$(set_color)          == Root(UID 0) Login shell (i.e. sudo bash)
-     $(set_color ered)Light Red$(set_color)    == Root(UID 0) Login shell (i.e. su -l or direct login)
-     $(set_color yellow)Yellow$(set_color)       == Root(UID 0) priviledges in non-login shell (i.e. su)
-     $(set_color eyellow)Light Yellow$(set_color) == SU to user other than root(UID 0)
-     $(set_color green)Green$(set_color)        == Normal user
+     \[$(set_color red)\]Red\[$(set_color)\]          == Root(UID 0) Login shell (i.e. sudo bash)
+     \[$(set_color ered)\]Light Red\[$(set_color)\]    == Root(UID 0) Login shell (i.e. su -l or direct login)
+     \[$(set_color yellow)\]Yellow\[$(set_color)\]       == Root(UID 0) priviledges in non-login shell (i.e. su)
+     \[$(set_color eyellow)\]Light Yellow\[$(set_color)\] == SU to user other than root(UID 0)
+     \[$(set_color green)\]Green\[$(set_color)\]        == Normal user
    @:
-     $(set_color ered)Light Red$(set_color)    == http_proxy environmental variable undefined.
-     $(set_color green)Green$(set_color)        == http_proxy environmental variable configured.
+     \[$(set_color ered)\]Light Red\[$(set_color)\]    == http_proxy environmental variable undefined.
+     \[$(set_color green)\]Green\[$(set_color)\]        == http_proxy environmental variable configured.
    HOST:
-     $(set_color red)Red$(set_color)          == Insecure remote connection (unknown type)
-     $(set_color yellow)Yellow$(set_color)       == Insecure remote connection (Telnet)
-     $(set_color eyellow)Light Yellow$(set_color) == Insecure remote connection (RSH)
-     $(set_color cyan)Cyan$(set_color)         == Secure remote connection (i.e. SSH)
-     $(set_color green)Green$(set_color)        == Local session
+     \[$(set_color red)\]Red\[$(set_color)\]          == Insecure remote connection (unknown type)
+     \[$(set_color yellow)\]Yellow\[$(set_color)\]       == Insecure remote connection (Telnet)
+     \[$(set_color eyellow)\]Light Yellow\[$(set_color)\] == Insecure remote connection (RSH)
+     \[$(set_color cyan)\]Cyan\[$(set_color)\]         == Secure remote connection (i.e. SSH)
+     \[$(set_color green)\]Green\[$(set_color)\]        == Local session
    GLOBAL VARIABLSE INFORMATION:
-     $(set_color ecyan)[venv:NAME]$(set_color)  == Name of the virtual envirnoment you are currently using if using
+     \[$(set_color ecyan)\][venv:NAME]\[$(set_color)\]  == Name of the virtual envirnoment you are currently using if using
                       python virtual_env
    CURRENT DIR INFORMATION:
-     $(set_color magenta)[svn:#:#]$(set_color)    == Display version of current svn directory
+     \[$(set_color magenta)\][svn:#:#]\[$(set_color)\]    == Display version of current svn directory
                   Will contain * at end if you got local modification
                   If two numbers, 1st is last updated version, 2nd is your version
                   If one number, your version is the last checked out
-     $(set_color magenta)[git:r#]$(set_color)     == Display version of current git directory
+     \[$(set_color magenta)\][git:r#]\[$(set_color)\]     == Display version of current git directory
                   Will contain * at end if you got local modification
    DYNAMIC SECTION:
        (If count is zero for any of the following, it will not appear)
-     $(set_color red)[es:#]$(set_color)       == Exit code of last command run
+     \[$(set_color red)\][es:#]\[$(set_color)\]       == Exit code of last command run
      [scr:#] ==== Number of detached screen sessions
-       $(set_color yellow)Yellow$(set_color)     == 1-2
-       $(set_color red)Red$(set_color)        == 3+
+       \[$(set_color yellow)\]Yellow\[$(set_color)\]     == 1-2
+       \[$(set_color red)\]Red\[$(set_color)\]        == 3+
      [bg:#]  ==== Number of backgrounded but still running jobs
-       $(set_color yellow)Yellow$(set_color)     == 1-10
-       $(set_color red)Red$(set_color)        == 11+
+       \[$(set_color yellow)\]Yellow\[$(set_color)\]     == 1-10
+       \[$(set_color red)\]Red\[$(set_color)\]        == 11+
      [stp:#] ==== Number of stopped (backgrounded) jobs
-       $(set_color yellow)Yellow$(set_color)     == 1-2
-       $(set_color red)Red$(set_color)        == 3+
+       \[$(set_color yellow)\]Yellow\[$(set_color)\]     == 1-2
+       \[$(set_color red)\]Red\[$(set_color)\]        == 3+
    CURRENT DIRECTORY:     (truncated to 1/3 screen width)
-     $(set_color red)Red$(set_color)          == Current user does not have write priviledges
-     $(set_color green)Green$(set_color)        == Current user does have write priviledges
+     \[$(set_color red)\]Red\[$(set_color)\]          == Current user does not have write priviledges
+     \[$(set_color green)\]Green\[$(set_color)\]        == Current user does have write priviledges
    NOTE:
      1.  Displays message on day change at midnight on the line above the
          prompt (Day changed to...).
@@ -118,13 +118,13 @@ function promptcmd () {
     fi
     case ${system_type} in
 	"crit"|"critical")
-	    local system_type_color="$(set_color red)"
+	    local system_type_color="\[$(set_color red)\]"
 	    ;;
 	"prod")
-	    local system_type_color="$(set_color yellow)"
+	    local system_type_color="\[$(set_color yellow)\]"
 	    ;;
 	"test")
-	    local system_type_color="$(set_color green)"
+	    local system_type_color="\[$(set_color green)\]"
 	    ;;
     esac
     if [ -z "${system_category}" ]; then
@@ -132,7 +132,7 @@ function promptcmd () {
 	    local system_category="${system_type}"
 	fi
     fi
-    [ -z "${system_category}" ] || PS1="${PS1}${system_type_color:-""}(${system_category})$(set_color) "
+    [ -z "${system_category}" ] || PS1="${PS1}${system_type_color:-""}(${system_category})\[$(set_color)\] "
 
     PS1="${PS1}${TITLEBAR}"
 
@@ -143,7 +143,7 @@ function promptcmd () {
 	else
             local today=$(date +%A)
             if [ "${DAY}" != "${today}" ]; then
-		PS1="${PS1}\n$(set_color green)Day changed to $(date '+%A, %d %B %Y').$(set_color)\n"
+		PS1="${PS1}\n\[$(set_color green)\]Day changed to $(date '+%A, %d %B %Y').\[$(set_color)\]\n"
 		export DAY=$today
 	    fi
 	fi
@@ -153,26 +153,26 @@ function promptcmd () {
     if [ ${UID} -eq 0 ] ; then
         if [ "${USER}" == "${LOGNAME}" ]; then
             if [[ ${SUDO_USER} ]]; then
-                PS1="${PS1}$(set_color red)\u$(set_color)"
+                PS1="${PS1}\[$(set_color red)\]\u\[$(set_color)\]"
             else
-                PS1="${PS1}$(set_color ered)\u$(set_color)"
+                PS1="${PS1}\[$(set_color ered)\]\u\[$(set_color)\]"
             fi
         else
-            PS1="${PS1}$(set_color yellow)\u$(set_color)"
+            PS1="${PS1}\[$(set_color yellow)\]\u\[$(set_color)\]"
         fi
     else
         if [ ${USER} == ${LOGNAME} ]; then
-            PS1="${PS1}$(set_color green)\u$(set_color)"
+            PS1="${PS1}\[$(set_color green)\]\u\[$(set_color)\]"
         else
-            PS1="${PS1}$(set_color eyellow)\u$(set_color)"
+            PS1="${PS1}\[$(set_color eyellow)\]\u\[$(set_color)\]"
         fi
     fi
 
     # HTTP Proxy var configured or not
     if [ -n "$http_proxy" ] ; then
-        PS1="${PS1}$(set_color green)@$(set_color)"
+        PS1="${PS1}\[$(set_color green)\]@\[$(set_color)\]"
     else
-        PS1="${PS1}$(set_color ered)@$(set_color)"
+        PS1="${PS1}\[$(set_color ered)\]@\[$(set_color)\]"
     fi
 
     # Host
@@ -180,30 +180,30 @@ function promptcmd () {
         SSH_FLAG=1
     fi
     if [ ${SSH_FLAG} -eq 1 ]; then
-       PS1="${PS1}$(set_color cyan)\h$(set_color) "
+       PS1="${PS1}\[$(set_color cyan)\h\[$(set_color)\] "
     elif [[ -n ${SESS_SRC} ]]; then
         if [ "${SESS_SRC}" == "(:0.0)" ]; then
-           PS1="${PS1}$(set_color green)\h$(set_color) "
+           PS1="${PS1}\[$(set_color green)\]\h\[$(set_color)\] "
         else
             local parent_process=$(ps -p $PPID -o comm | tail -n 1)
             if [[ "$parent_process" == "in.rlogind*" ]]; then
-                PS1="${PS1}$(set_color eyellow)\h$(set_color) "
+                PS1="${PS1}\[$(set_color eyellow)\]\h\[$(set_color)\] "
             elif [[ "$parent_process" == "in.telnetd*" ]]; then
-                PS1="${PS1}$(set_color yellow)\h$(set_color) "
+                PS1="${PS1}\[$(set_color yellow)\]\h\[$(set_color)\] "
             else
-                PS1="${PS1}$(set_color ered)\h$(set_color) "
+                PS1="${PS1}\[$(set_color ered)\]\h\[$(set_color)\] "
             fi
         fi
     elif [[ "${SESS_SRC}" == "" ]]; then
-        PS1="${PS1}$(set_color green)\h$(set_color) "
+        PS1="${PS1}\[$(set_color green)\]\h\[$(set_color)\] "
     else
-        PS1="${PS1}$(set_color red)\h$(set_color) "
+        PS1="${PS1}\[$(set_color red)\]\h\[$(set_color)\] "
     fi
 
     # Check for python virtualenv
     if [[ $VIRTUAL_ENV ]]; then
       VIRTNAME=$(basename $VIRTUAL_ENV)
-      PS1="${PS1}$(set_color ecyan)[venv:${VIRTNAME}]$(set_color) "
+      PS1="${PS1}\[$(set_color ecyan)[venv:${VIRTNAME}]\[$(set_color)\] "
     fi
 
     # SVN status if .svn exist
@@ -212,7 +212,7 @@ function promptcmd () {
 	    local DIRTY REV=$(svnversion . 2>/dev/null)
 	    [ "$REV" ] || REV='?'
 	    [ "$(svn st &> /dev/null)" ] && DIRTY='*'
-            PS1="${PS1}$(set_color magenta)[svn:${REV}${DIRTY}]$(set_color) "
+            PS1="${PS1}\[$(set_color magenta)\][svn:${REV}${DIRTY}]\[$(set_color)\] "
 	fi
     fi
 
@@ -223,21 +223,21 @@ function promptcmd () {
 	if [ $? -ne 128 ]; then
 	    [[ "$STATUS" == *'working directory clean'* ]] || DIRTY='*'
 	    GITSTATUS="($(git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* //')$DIRTY)"
-            PS1="${PS1}$(set_color magenta)[git:${GITSTATUS}]$(set_color) "
+            PS1="${PS1}\[$(set_color magenta)\][git:${GITSTATUS}]\[$(set_color)\] "
 	fi
     fi
 
     # Exit status of the last command run. Must run the command itself from the PS1, so we must pass on this part
 
-    PS1="${PS1}\`let exitstatus=\$? ; if [[ \${exitstatus} != 0 ]] ; then echo -ne \"\$(set_color red)[es:\${exitstatus}]\$(set_color) \" ; fi\`"
+    PS1="${PS1}\`let exitstatus=\$? ; if [[ \${exitstatus} != 0 ]] ; then echo -ne \"\\[$(set_color red)\][es:\${exitstatus}]\\[$(set_color)\] \" ; fi\`"
 
     # Detached Screen Sessions
     if which screen &> /dev/null; then
       local DTCHSCRN=$(screen -ls | grep -c Detach )
       if [ ${DTCHSCRN} -gt 2 ]; then
-          PS1="${PS1}$(set_color red)[scr:${DTCHSCRN}]$(set_color) "
+          PS1="${PS1}\[$(set_color red)\][scr:${DTCHSCRN}]\[$(set_color)\] "
       elif [ ${DTCHSCRN} -gt 0 ]; then
-          PS1="${PS1}$(set_color yellow)[scr:${DTCHSCRN}]$(set_color) "
+          PS1="${PS1}\[$(set_color yellow)\][scr:${DTCHSCRN}]\[$(set_color)\] "
       fi
     fi
 
@@ -246,17 +246,17 @@ function promptcmd () {
     # Backgrounded running jobs
     local BKGJBS=$(jobs -r | wc -l | sed -e 's/[^0-9]//g' )
     if [ ${BKGJBS} -gt 2 ]; then
-        PS1="${PS1}$(set_color red)[bg:${BKGJBS}]$(set_color) "
+        PS1="${PS1}\[$(set_color red)\][bg:${BKGJBS}]\[$(set_color)\] "
     elif [ ${BKGJBS} -gt 0 ]; then
-        PS1="${PS1}$(set_color yellow)[bg:${BKGJBS}]$(set_color) "
+        PS1="${PS1}\[$(set_color yellow)\][bg:${BKGJBS}]\[$(set_color)\] "
     fi
 
     # Stopped Jobs
     local STPJBS=$(jobs -s | wc -l | sed -e 's/[^0-9]//g' )
     if [ ${STPJBS} -gt 2 ]; then
-        PS1="${PS1}$(set_color red)[stp:${STPJBS}]$(set_color) "
+        PS1="${PS1}\[$(set_color red)\][stp:${STPJBS}]\[$(set_color)\] "
     elif [ ${STPJBS} -gt 0 ]; then
-        PS1="${PS1}$(set_color yellow)[stp:${STPJBS}]$(set_color) "
+        PS1="${PS1}\[$(set_color yellow)\][stp:${STPJBS}]\[$(set_color)\] "
     fi
 
     # Bracket {
@@ -264,52 +264,52 @@ function promptcmd () {
     if [ ${UID} -eq 0 ]; then
         if [ "${USER}" == "${LOGNAME}" ]; then
             if [[ ${SUDO_USER} ]]; then
-                PS1="${PS1}$(set_color red)"
+                PS1="${PS1}\[$(set_color red)\]"
             else
-                PS1="${PS1}$(set_color ered)"
+                PS1="${PS1}\[$(set_color ered)\]"
             fi
         else
-            PS1="${PS1}$(set_color yellow)"
+            PS1="${PS1}\[$(set_color yellow)\]"
         fi
     else
         if [ "${USER}" == "${LOGNAME}" ]; then
-            PS1="${PS1}$(set_color green)"
+            PS1="${PS1}\[$(set_color green)\]"
         else
-            PS1="${PS1}$(set_color eyellow)"
+            PS1="${PS1}\[$(set_color eyellow)\]"
         fi
     fi
     PS1="${PS1}{ "
 
     # Working directory
     if [ -w "${PWD}" ]; then
-        PS1="${PS1}$(set_color green)$(prompt_workingdir)"
+        PS1="${PS1}\[$(set_color green)\]$(prompt_workingdir)"
     else
-        PS1="${PS1}$(set_color red)$(prompt_workingdir)"
+        PS1="${PS1}\[$(set_color red)\]$(prompt_workingdir)"
     fi
 
     # Closing bracket } and $\#
     # FIXME: duplicate code with user
     if [ ${UID} -eq 0 ]; then
-        user_mark="$(set_color red)#"
+        user_mark="\[$(set_color red)\]#"
         if [ "${USER}" == "${LOGNAME}" ]; then
             if [[ ${SUDO_USER} ]]; then
-                PS1="${PS1}$(set_color red)"
+                PS1="${PS1}\[$(set_color red)\]"
             else
-                PS1="${PS1}$(set_color ered)"
+                PS1="${PS1}\[$(set_color ered)\]"
             fi
         else
-            PS1="${PS1}$(set_color yellow)"
+            PS1="${PS1}\[$(set_color yellow)\]"
         fi
     else
-        user_mark="$(set_color green)$"
+        user_mark="\[$(set_color green)\]$"
         if [ "${USER}" == "${LOGNAME}" ]; then
-            PS1="${PS1}$(set_color green)"
+            PS1="${PS1}\[$(set_color green)\]"
         else
-            PS1="${PS1}$(set_color eyellow)"
+            PS1="${PS1}\[$(set_color eyellow)\]"
         fi
     fi
 
-    PS1="${PS1} }$user_mark$(set_color) "
+    PS1="${PS1} }$user_mark\[$(set_color)\] "
 }
 
 # Trim working dir to 1/3 the screen width
